### ISSUE TITLE
Support for java.time.ZonedDateTime

### ISSUE THREAD

**Issue by argatxa** [hazendaz/javabean-tester#235]
Hello all, 

Could be possible to add support for java.time.ZonedDateTime? 

WARN com.codebox.bean.ValueBuilder - Unable to build value for class 'java.time.ZonedDateTime', please raise ticket with JavaBeanTester for desired support

Cheers.
a

**Comment by hazendaz** [comment]
@argatxa Sure, is it possible you could open a pull request for this?  Look in ValueBuilder class.

**Comment by argatxa** [comment]
I have a PR ready, is there any quickguide on how to push? I am trying to push to a feature branch so I can do the PR but It is giving me access denied. 

10:33:20.113: [javabean-tester] git -c credential.helper= -c core.quotepath=false -c log.showSignature=false push --progress --porcelain origin refs/heads/master:feature/zonedDateTime
remote: Permission to hazendaz/javabean-tester.git denied to argatxa.
fatal: unable to access 'https://github.com/hazendaz/javabean-tester.git/': The requested URL returned error: 403

**Comment by argatxa** [comment]
Done --> https://github.com/hazendaz/javabean-tester/pull/236

**Comment by hazendaz** [comment]
Resolved in #236

**Comment by hazendaz** [comment]
@argatxa 2.3.1 is released now.
