### ISSUE TITLE
ClassInstance.newInstance(Class<T> clazz) does not reliably use the same constructor

### ISSUE THREAD

**Issue by Thunderforge** [hazendaz/javabean-tester#265]
Consider the following class, which contains two constructors:

```java
public class Foo {
    private String id;
    private String value;

    public Foo() {
        // no-args constructor
    }

    public Foo(String id, String value) {
        this.id = id;
        this.value = value;
    }

    // Getters, setters, equals, hashcode, and toString()
}
```

This is tested as follows:

```java
public class FooTest {

    @Test
    void testJavaBean() {
        JavaBeanTester.builder(FooTest.class)
                .checkEquals()
                .loadData()
                .test();
    }
}
```

In version 1.3.1, sometimes the test passes and sometimes it fails with:

```
expected: not equal but was: <Foo[id=TEST_VALUE,value=TEST_VALUE]>
org.opentest4j.AssertionFailedError: expected: not equal but was: <Foo[id=TEST_VALUE,value=TEST_VALUE]>
	at org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:39)
	at org.junit.jupiter.api.AssertNotEquals.failEqual(AssertNotEquals.java:276)
	at org.junit.jupiter.api.AssertNotEquals.assertNotEquals(AssertNotEquals.java:265)
	at org.junit.jupiter.api.AssertNotEquals.assertNotEquals(AssertNotEquals.java:260)
	at org.junit.jupiter.api.Assertions.assertNotEquals(Assertions.java:2798)
	at com.codebox.bean.JavaBeanTesterWorker.equalsHashCodeToStringSymmetricTest(JavaBeanTesterWorker.java:436)
	at com.codebox.bean.JavaBeanTesterWorker.test(JavaBeanTesterWorker.java:170)
	at com.codebox.bean.JavaBeanTesterBuilder.test(JavaBeanTesterBuilder.java:198)
	at com.example.FooTest.testJavaBean(FooTest.java:18)
```

This bug report will examine the reasons why.

## Problem

When calling [`ClassInstance.newInstance(Class<T> clazz)`](https://github.com/hazendaz/javabean-tester/blob/e42ad87a9b9f24b745b861f956e8aa5cc67ec19a/src/main/java/com/codebox/instance/ClassInstance.java#L44), sometimes an instance with the no-argument constructor is returned (`Foo[id=null,value=null]`) and sometimes an instance with the two-argument constructor is returned (`Foo[id=TEST_VALUE,value=TEST_VALUE]`).

For instance, this is called [in `JavaBeanTesterWorker.equalsHashCodeToStringSymmetricTest()`](https://github.com/hazendaz/javabean-tester/blob/e42ad87a9b9f24b745b861f956e8aa5cc67ec19a/src/main/java/com/codebox/bean/JavaBeanTesterWorker.java#L399) with the following code:

```java
 // Create Instances
final T x = new ClassInstance<T>().newInstance(this.clazz);
final T y = new ClassInstance<T>().newInstance(this.clazz);

// [Other tests]

if (classHasSetters(this.clazz)) {
    // Populate Side X
    JavaBeanTesterWorker.load(this.clazz, x, this.loadData);

    // ReTest Equals (flip)
    Assertions.assertNotEquals(y, x, String
         .format(".equals() should be consistent for two empty objects of type %s", this.clazz.getName()));
}
```

In this example, the expectation is that `new ClassInstance<T>().newInstance(this.clazz)` creates a zero-argument constructor version of `x` and `y` (where both are `Foo[id=null,value=null]`). Then values are added to `x` such that it equals `Foo[id=TEST_VALUE,value=TEST_VALUE]`, which should not equal the value of `y`.

However, if `new ClassInstance<T>().newInstance(this.clazz)` returns the two-argument constructor of `Foo` for `y`, then it equals `Foo[id=TEST_VALUE,value=TEST_VALUE]`. The values of `x` will be overwritten regardless of which version of the constructor is returned. But in this case, both `x` and `y` are equal when they aren't expected to be.

## Analysis

It appears that the issue is in the [constructor iteration of new instance](https://github.com/hazendaz/javabean-tester/blob/e42ad87a9b9f24b745b861f956e8aa5cc67ec19a/src/main/java/com/codebox/instance/ClassInstance.java#L45). Basically, the algorithm is:

1. Get all constructors via `clazz.getConstructors()`
2. Iterate over each of constructor
3. Try to return `(T) constructor.newInstance(values)` (this effectively returns the first validly produced constructor)

The problem is that the order of `clazz.getConstructors()` does not appear to be guaranteed (tested on OpenJDK 11.0.2). So sometimes the zero-argument constructor is first and thus an instance of it is returned and sometimes the two-argument constructor is first and thus an instance of it is returned.

## Solution

At the bare minimum, the result of `new ClassInstance<T>().newInstance(this.clazz)` should consistently be an instance created using the same constructor.

However, we should also avoid situations where the order of constructors produces different results from that method. Therefore, I don't think we want to just rely on the "first" method.

Perhaps the best solution is to examine when we call `new ClassInstance<T>().newInstance(this.clazz)` and determine whether we want a zero-argument constructor (as in `JavaBeanTesterWorker.equalsHashCodeToStringSymmetricTest()`) and when we want other constructors. That way, we don't leave it up to chance.

**Comment by hazendaz** [comment]
@Thunderforge Please try latest version and confirm if the same issue exists.  Current version is 2.3.1.

**Comment by hazendaz** [comment]
note: if you are using jdk 7 still thus version 1.x, you can split the classpath so you can use jdk 8 on tests only.

**Comment by Thunderforge** [comment]
Yes, this behavior was observed with Javabean Tester 2.3.1 and JDK 11.

**Comment by hazendaz** [comment]
@Thunderforge I patched master.   Its not perfect as you have outlined but should be a good improvement.  Can you give the lastest master and try and let me know if that works out better for you in this situation?

**Comment by hazendaz** [comment]
closing ticket, fix in master as applied on 2/14 being released now.  If issue still is a problem afterwards, please open new ticket.
