### ISSUE TITLE
Does not detect copy paste errors for "getter" / "setter" logic

### ISSUE THREAD

**Issue by garysclark** [hazendaz/javabean-tester#30]
Because the same test data is used for specific types (e.g. "TEST_VALUE" for String), "getter" / "setter" tests pass even if there was a copy paste error in the logic.
Example:
	public void setType(String type) {
		this.type = type;
	}

	public String getType() {
		return model;
	}
Where "model" is another String property in the class.
This logic currently passes when running the following:

JavaBeanTester.builder(RvModel.class).loadData().skipStrictSerializable().test();

**Comment by hazendaz** [comment]
Released fix in 2.0.0
