### ISSUE TITLE
java.time.OffsetDateTime not handled by javabean-tester

### ISSUE THREAD

**Issue by DYKWIA** [hazendaz/javabean-tester#560]
I have some bean classes that use java.math.BigDecimal, java.util.Set and java.time.OffsetDateTime. When these are encountered by javabean-tester, the following is output :

Unable to build value for class 'java.math.BigDecimal', please raise ticket with JavaBeanTester for desired support.
Unable to build value for class 'java.time.OffsetDateTime', please raise ticket with JavaBeanTester for desired support.
Unable to build value for class 'java.util.Set', please raise ticket with JavaBeanTester for desired support.

So, I'm raising a ticket :)

Thanks

**Comment by hazendaz** [comment]
Added 'java.tim.OffsetDateTime' to master now.  Will be in final 2.5.0
