### ISSUE TITLE
Constructors testing

### ISSUE THREAD

**Issue by Toilal** [hazendaz/javabean-tester#8]
Would be usefull and add support for testing of constructor.

Some JavaBean have constructors parameters that match properties, and this should be checked.

**Comment by hazendaz** [comment]
Merged in SHA:2f6f143

**Comment by hazendaz** [comment]
I would like to keep this open in order to add another type of constructor test for a private static util class.

**Comment by hazendaz** [comment]
Private constructor tests added for utlity classes.  This uses stub into builder pattern as "JavabeanTester.builder(XXX.class).testPrivateConstructor()".  This isn't a perfect solution but makes it simple to test these private constructors which is otherwise duplicate code over and over :)
